# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/c-t9

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/c-t9

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/c-t9/CMakeFiles /tmp/c-t9/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/c-t9/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named t9

# Build rule for target.
t9: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t9
.PHONY : t9

# fast build rule for target.
t9/fast:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/build
.PHONY : t9/fast

libraries/list/iterator.o: libraries/list/iterator.c.o

.PHONY : libraries/list/iterator.o

# target to build an object file
libraries/list/iterator.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/iterator.c.o
.PHONY : libraries/list/iterator.c.o

libraries/list/iterator.i: libraries/list/iterator.c.i

.PHONY : libraries/list/iterator.i

# target to preprocess a source file
libraries/list/iterator.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/iterator.c.i
.PHONY : libraries/list/iterator.c.i

libraries/list/iterator.s: libraries/list/iterator.c.s

.PHONY : libraries/list/iterator.s

# target to generate assembly for a file
libraries/list/iterator.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/iterator.c.s
.PHONY : libraries/list/iterator.c.s

libraries/list/list.o: libraries/list/list.c.o

.PHONY : libraries/list/list.o

# target to build an object file
libraries/list/list.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/list.c.o
.PHONY : libraries/list/list.c.o

libraries/list/list.i: libraries/list/list.c.i

.PHONY : libraries/list/list.i

# target to preprocess a source file
libraries/list/list.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/list.c.i
.PHONY : libraries/list/list.c.i

libraries/list/list.s: libraries/list/list.c.s

.PHONY : libraries/list/list.s

# target to generate assembly for a file
libraries/list/list.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/list.c.s
.PHONY : libraries/list/list.c.s

libraries/list/list_node.o: libraries/list/list_node.c.o

.PHONY : libraries/list/list_node.o

# target to build an object file
libraries/list/list_node.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/list_node.c.o
.PHONY : libraries/list/list_node.c.o

libraries/list/list_node.i: libraries/list/list_node.c.i

.PHONY : libraries/list/list_node.i

# target to preprocess a source file
libraries/list/list_node.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/list_node.c.i
.PHONY : libraries/list/list_node.c.i

libraries/list/list_node.s: libraries/list/list_node.c.s

.PHONY : libraries/list/list_node.s

# target to generate assembly for a file
libraries/list/list_node.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/libraries/list/list_node.c.s
.PHONY : libraries/list/list_node.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/main.c.s
.PHONY : src/main.c.s

src/t9/corpus.o: src/t9/corpus.c.o

.PHONY : src/t9/corpus.o

# target to build an object file
src/t9/corpus.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/corpus.c.o
.PHONY : src/t9/corpus.c.o

src/t9/corpus.i: src/t9/corpus.c.i

.PHONY : src/t9/corpus.i

# target to preprocess a source file
src/t9/corpus.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/corpus.c.i
.PHONY : src/t9/corpus.c.i

src/t9/corpus.s: src/t9/corpus.c.s

.PHONY : src/t9/corpus.s

# target to generate assembly for a file
src/t9/corpus.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/corpus.c.s
.PHONY : src/t9/corpus.c.s

src/t9/io.o: src/t9/io.c.o

.PHONY : src/t9/io.o

# target to build an object file
src/t9/io.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/io.c.o
.PHONY : src/t9/io.c.o

src/t9/io.i: src/t9/io.c.i

.PHONY : src/t9/io.i

# target to preprocess a source file
src/t9/io.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/io.c.i
.PHONY : src/t9/io.c.i

src/t9/io.s: src/t9/io.c.s

.PHONY : src/t9/io.s

# target to generate assembly for a file
src/t9/io.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/io.c.s
.PHONY : src/t9/io.c.s

src/t9/math.o: src/t9/math.c.o

.PHONY : src/t9/math.o

# target to build an object file
src/t9/math.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/math.c.o
.PHONY : src/t9/math.c.o

src/t9/math.i: src/t9/math.c.i

.PHONY : src/t9/math.i

# target to preprocess a source file
src/t9/math.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/math.c.i
.PHONY : src/t9/math.c.i

src/t9/math.s: src/t9/math.c.s

.PHONY : src/t9/math.s

# target to generate assembly for a file
src/t9/math.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/math.c.s
.PHONY : src/t9/math.c.s

src/t9/model.o: src/t9/model.c.o

.PHONY : src/t9/model.o

# target to build an object file
src/t9/model.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/model.c.o
.PHONY : src/t9/model.c.o

src/t9/model.i: src/t9/model.c.i

.PHONY : src/t9/model.i

# target to preprocess a source file
src/t9/model.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/model.c.i
.PHONY : src/t9/model.c.i

src/t9/model.s: src/t9/model.c.s

.PHONY : src/t9/model.s

# target to generate assembly for a file
src/t9/model.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/model.c.s
.PHONY : src/t9/model.c.s

src/t9/node.o: src/t9/node.c.o

.PHONY : src/t9/node.o

# target to build an object file
src/t9/node.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/node.c.o
.PHONY : src/t9/node.c.o

src/t9/node.i: src/t9/node.c.i

.PHONY : src/t9/node.i

# target to preprocess a source file
src/t9/node.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/node.c.i
.PHONY : src/t9/node.c.i

src/t9/node.s: src/t9/node.c.s

.PHONY : src/t9/node.s

# target to generate assembly for a file
src/t9/node.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/node.c.s
.PHONY : src/t9/node.c.s

src/t9/path.o: src/t9/path.c.o

.PHONY : src/t9/path.o

# target to build an object file
src/t9/path.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/path.c.o
.PHONY : src/t9/path.c.o

src/t9/path.i: src/t9/path.c.i

.PHONY : src/t9/path.i

# target to preprocess a source file
src/t9/path.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/path.c.i
.PHONY : src/t9/path.c.i

src/t9/path.s: src/t9/path.c.s

.PHONY : src/t9/path.s

# target to generate assembly for a file
src/t9/path.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/path.c.s
.PHONY : src/t9/path.c.s

src/t9/timer.o: src/t9/timer.c.o

.PHONY : src/t9/timer.o

# target to build an object file
src/t9/timer.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/timer.c.o
.PHONY : src/t9/timer.c.o

src/t9/timer.i: src/t9/timer.c.i

.PHONY : src/t9/timer.i

# target to preprocess a source file
src/t9/timer.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/timer.c.i
.PHONY : src/t9/timer.c.i

src/t9/timer.s: src/t9/timer.c.s

.PHONY : src/t9/timer.s

# target to generate assembly for a file
src/t9/timer.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/timer.c.s
.PHONY : src/t9/timer.c.s

src/t9/tree.o: src/t9/tree.c.o

.PHONY : src/t9/tree.o

# target to build an object file
src/t9/tree.c.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/tree.c.o
.PHONY : src/t9/tree.c.o

src/t9/tree.i: src/t9/tree.c.i

.PHONY : src/t9/tree.i

# target to preprocess a source file
src/t9/tree.c.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/tree.c.i
.PHONY : src/t9/tree.c.i

src/t9/tree.s: src/t9/tree.c.s

.PHONY : src/t9/tree.s

# target to generate assembly for a file
src/t9/tree.c.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/src/t9/tree.c.s
.PHONY : src/t9/tree.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... t9"
	@echo "... edit_cache"
	@echo "... libraries/list/iterator.o"
	@echo "... libraries/list/iterator.i"
	@echo "... libraries/list/iterator.s"
	@echo "... libraries/list/list.o"
	@echo "... libraries/list/list.i"
	@echo "... libraries/list/list.s"
	@echo "... libraries/list/list_node.o"
	@echo "... libraries/list/list_node.i"
	@echo "... libraries/list/list_node.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/t9/corpus.o"
	@echo "... src/t9/corpus.i"
	@echo "... src/t9/corpus.s"
	@echo "... src/t9/io.o"
	@echo "... src/t9/io.i"
	@echo "... src/t9/io.s"
	@echo "... src/t9/math.o"
	@echo "... src/t9/math.i"
	@echo "... src/t9/math.s"
	@echo "... src/t9/model.o"
	@echo "... src/t9/model.i"
	@echo "... src/t9/model.s"
	@echo "... src/t9/node.o"
	@echo "... src/t9/node.i"
	@echo "... src/t9/node.s"
	@echo "... src/t9/path.o"
	@echo "... src/t9/path.i"
	@echo "... src/t9/path.s"
	@echo "... src/t9/timer.o"
	@echo "... src/t9/timer.i"
	@echo "... src/t9/timer.s"
	@echo "... src/t9/tree.o"
	@echo "... src/t9/tree.i"
	@echo "... src/t9/tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

